# path to root directory
# Defaults to current working directory
root_dir: /root/lanyun-tmp/diffesm-main

# Path to directory where processed netCDF4 files are stored
data_dir: /root/lanyun-tmp/data/prepared_data

# Path to where the JSON files describing the data are stored
json_data_dir: /root/lanyun-tmp/data/json

# Path to where our generated samples will be saved
save_dir: /root/lanyun-tmp/data/generated

# Path to where our quantiles will be saved to and accessed
quantile_dir: /root/lanyun-tmp/data/quantiles
